include:
  - Application.yml

name: ${PROJECT_NAME}

configs:
  Debug: debug
  Release: release

options:
  deploymentTarget:
    iOS: "17.0"
  defaultConfig: Release

settings:
  base:
    SWIFT_VERSION: "6.0"
    CODE_SIGN_STYLE: Automatic
